DATASETS = ["csu", "cars", "bakery", "students", "marathon", "airlines", "wine", "inn"]

def dataset(name)
  file "datasets/#{name}.zip" do
    url = "http://users.csc.calpoly.edu/~dekhtyar/365-Winter2013/data/#{name.upcase}/#{name.upcase}.zip"
    sh "curl #{url} > datasets/#{name}.zip"
  end

  file "datasets/#{name}" => "datasets/#{name}.zip" do
    cd "datasets" do
      sh "unzip #{name}.zip -d #{name}"
    end
  end
end

def datasets(*names)
  names.each do |name|
    dataset name
  end
end

datasets *DATASETS

file "datasets" => DATASETS.map { |d| "datasets/#{d}" }

task "mysql:setup" => "mysql:setup:all"
task "mysql:import" => "mysql:import:all"

namespace :mysql do
  namespace :setup do
    DATASETS.each do |dataset|
      task dataset => :datasets do
        sh "mysql -u root < setup/#{dataset}-setup.sql"
      end
    end

    task :all => DATASETS
  end

  namespace :import do
    task :airlines => "mysql:setup" do
      sh "ruby ./import/AIRLINES-insert.rake"
    end

    task :bakery => "mysql:setup" do
      sh "ruby ./import/BAKERY-insert.rake"
    end

    task :inn => "mysql:setup" do
      sh "ruby ./import/INN-insert.rake"
    end

    task :marathon => "mysql:setup" do
      sh "ruby ./import/MARATHON-insert.rake"
    end

    task :students => "mysql:setup" do
      sh "ruby ./import/STUDENTS-insert.rake"
    end

    task :wine do
      sh "ruby ./import/WINE-insert.rake"
    end

    task :all => [:airlines, :bakery, :inn, :marathon, :students]
  end
end
