require_relative "./lib/dataset_mapper"
require_relative "./tasks/datasets"
require_relative "./tasks/import_database"
require_relative "./tasks/setup_database"
require_relative "./tasks/clobber"

DATASETS = ["csu", "cars", "bakery", "students", "marathon", "airlines", "wine", "inn"]

datasets *DATASETS

directory "datasets"

task "download_datasets" => ["datasets"].concat(DATASETS.map { |d| "datasets/#{d}" })
task "mysql"         => "mysql:import"
task "mysql:setup"   => "mysql:setup:all"
task "mysql:import"  => "mysql:import:all"
task "mysql:clobber" => "mysql:clobber:all"
task "mysql:rebuild" => "mysql:rebuild:all"

namespace :mysql do
  namespace :setup do
    DATASETS.each do |dataset|
      setup_database dataset => :download_datasets do
        sh "mysql -u root < setup/#{dataset}-setup.sql"
      end
    end

    task :all => DATASETS
  end

  namespace :import do
    DATASETS.each do |dataset|
      import_database dataset => "mysql:setup:#{dataset}" do
        sh "ruby ./import/#{dataset.upcase}-insert.rake"
      end
    end

    task :all => DATASETS
  end

  namespace :clobber do
    DATASETS.each do |dataset|
      clobber dataset
    end

    task :all => DATASETS
  end

  namespace :rebuild do
    DATASETS.each do |dataset|
      task dataset => ["mysql:clobber:#{dataset}", "mysql:import:#{dataset}"]
    end

    task :all => DATASETS
  end
end
